version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports: -5432:5432
  web:
    build: .
    command: python django-app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      DEBUG: ${DEBUG}
      DJANGO_DB_NAME: ${POSTGRES_DB}
      DJANGO_DB_USER: ${POSTGRES_USER}
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: ${POSTGRES_PORT}

volumes:
  postgres_data:
